---
title: "Árvores nativas"
author: "Heron Hilário"
date: "5/11/2022"
output: 
  html_document:
    code_download: yes
    theme: flatly
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
{library(Biostrings)
library(DECIPHER)
library(dplyr)
library(stringr)
library(ggtree)
library(RColorBrewer)
}
```

# Fazendo árvores a partir de sequências

```{r,echo=TRUE, eval=FALSE}

# Read DNA from fastas ----

## A função readDNAStringSet() do pacote Biostrings é chamada para criar um objeto 
## para armazenar as sequências de DNA do DB (objeto db_fasta) e das ASVs 
## identificadas no pipeline (asvs_fasta). A flag RemoveGaps() do pacote DECIPHER
## é utilizada para remover os gaps ("-" ou ".") que estejam nas sequências.

## As many as you want (for the same region!)
# dna_fasta_x <- Biostrings::readDNAStringSet(filepath = "/home/gabriel/projetos/db-LGC/data/mai22/LGC12Sdb_252seqs-mai22-order_clust.fasta") %>%
#   DECIPHER::RemoveGaps()

{
# Read DB
db_fasta <- Biostrings::readDNAStringSet(filepath = "/home/heron/prjcts/eDNA_fish/DB/mai22/DB/LGC12Sdb_251seqs-mai22-pretty_names_noGaps.fasta") %>%
  DECIPHER::RemoveGaps()

# Visualizar as seqs do db
BrowseSeqs(db_fasta)

# Read ASVs 
asvs_fasta <- Biostrings::readDNAStringSet(filepath = "/home/gabriel/projetos/lagoa_ingleses/results/tree/2023/ASVs_001.fas") %>%
  DECIPHER::RemoveGaps()

# Visualizar as seqs das ASVs
BrowseSeqs(asvs_fasta)
}

# Alinhar as ASVs com DB ----

## Necessario para observar onde as ASVs irao alinha nas sequencias do DB

# ASVs versus DB 
  dna_fasta <- c(db_fasta, asvs_fasta) %>% unique() %>% RemoveGaps()
  
# Alinhar as seqs do banco e das ASVs
dna_fasta_algn <- DECIPHER::AlignSeqs(myXStringSet = dna_fasta, 
                                      refinements = 100,
                                      iterations = 100,
                                      verbose = TRUE)

# Checar o alinhamento
BrowseSeqs(dna_fasta_algn)

## Podemos ver que diversas ASVs alinharam-se a uma regiao diferente do DB.
## Primeiro devemos cortar do DB a regiao alem da que foi alinhado o primer REV e depois retirar as ASVs nao alinhadas

# Trim DB ----

# Encontrar o primer nas seqs

## Encontrar a região do primer reverse nas seqs, isso deve ser feito para alinhar as ASVs apenas na regiao adequada.
## Deve ser feito manualmente :/ Ctrl+F no browser
## Identify informative region (EX: amplicon)

## Select MiFish Amplicon
#FWD = GTCGGTAAAACTCGTGCCAGC 
#REV = CATAGTGGGGTATCTAATCCCAGTTTG  
DNAStringSet("CATAGTGGGGTATCTAATCCCAGTTTG") %>% 
  reverseComplement()
#REV (rev comp) = CAAACTGGGATTAGATACCCCACTATG

## Based on your visualization, select only the region common to all species
db_fasta_algn <- DECIPHER::AlignSeqs(myXStringSet = db_fasta, 
                                      refinements = 100,
                                      iterations = 100,
                                      verbose = TRUE)
DECIPHER::BrowseSeqs(db_fasta_algn)

## Procurar pela sequência acima no alinhamento dna_fasta_algn e definir
## qual a região a ser trimada. Percebemos que é no nt 251

# Cut your alignment 
dna_fasta_algn_cut <- Biostrings::subseq(x = db_fasta_algn,start = 1, end = 251) 

# Visualizar o alinhamento do DB após o corte
BrowseSeqs(dna_fasta_algn_cut)

# Orient nucleotides ----

## Orients nucleotide sequences to match the directionality and complementarity of specified reference sequences
dna_fasta_or <- DECIPHER::OrientNucleotides(dna_fasta,
                                            reference = which.max(width(db_fasta)),
                                            type = "sequences", 
                                            orientation = "all",
                                            threshold = 0.05,
                                            verbose = TRUE,
                                            processors = 1)

# Visualizar as seqs após a orientação
BrowseSeqs(dna_fasta_or)
BrowseSeqs(db_fasta)

# Filtrar as Seqs ----

# Filtrar as seqs por tamanho
# dna_fasta_fil <- dna_fasta_or[names(dna_fasta_or[width(dna_fasta_or) > 164])] ## não irei utilizar esse filtro, ja que existem
                                                                                ## sequencias com tamanho grande porem que sao muito 
                                                                                ## divergentes. Irei filtrar pelo nome, abaixo

# Filtrar as seqs pelo nome
## NOTE: customize as you want

# Lista contendo os headers das ASVs que possuem sequencias discrepantes em relacao ao resto
asvs_to_remove <- c("ASV_11_195bp_merged|Cichlidae|NA|NA|Cichlidae",
                    "ASV_204_85bp_merged|NA|NA|NA|NA",
                    "ASV_201_93bp_merged|NA|NA|NA|NA",
                    "ASV_209_81bp_merged|NA|NA|NA|NA",
                    "ASV_208_81bp_merged|NA|NA|NA|NA",
                    "ASV_210_76bp_merged|NA|NA|NA|NA",
                    "ASV_203_86bp_merged|NA|NA|NA|NA",
                    "ASV_200_122bp_merged|NA|NA|NA|NA",
                    "ASV_202_92bp_merged|NA|NA|NA|NA",
                    "ASV_193_153bp_merged|Characidae|NA|NA|Characidae",
                    "ASV_191_159bp_merged|NA|NA|NA|NA",
                    "ASV_188_164bp_merged|NA|NA|NA|NA",
                    "ASV_189_164bp_merged|NA|NA|NA|NA",
                    "ASV_24_191bp_merged|NA|NA|NA|NA",
                    "ASV_31_178bp_merged|NA|NA|NA|NA",
                    "ASV_197_138bp_merged|NA|NA|NA|NA",
                    "ASV_13_194bp_merged|Characidae|Moenkhausia|Moenkhausia costae|Moenkhausia costae",
                    "ASV_14_194bp_merged|Erythrinidae|Hoplias|Hoplias malabaricus|Hoplias malabaricus/sp",
                    "ASV_15_194bp_merged|Erythrinidae|Hoplias|NA|Hoplias brasiliensis/intermedius",
                    "ASV_10_195bp_merged|Pimelodidae|Rhamdia|Rhamdia quelen|Rhamdia quelen",
                    "ASV_23_192bp_merged|Cichlidae|Oreochromis|Oreochromis niloticus|NA niloticus/rendalli",
                    "ASV_4_201bp_merged|NA|NA|NA|NA",
                    "ASV_16_193bp_merged|NA|NA|NA|NA",
                    "ASV_88_169bp_merged|NA|NA|NA|NA",
                    "ASV_211_65bp_merged|NA|NA|NA|NA",
                    "ASV_198_135bp_merged|NA|NA|NA|NA",
                    "ASV_199_130bp_merged|NA|NA|NA|NA",
                    "ASV_195_145bp_merged|NA|NA|NA|NA",
                    "ASV_17_193bp_merged|NA|NA|NA|NA",
                    "ASV_27_182bp_merged|NA|NA|NA|NA",
                    "ASV_207_83bp_merged|Loricariidae|Harttia|NA|Harttia",
                    "ASV_206_83bp_merged|NA|NA|NA|NA",
                    "ASV_194_146bp_merged|NA|NA|NA|NA",
                    "ASV_205_83bp_merged|NA|NA|NA|NA",
                    "ASV_1_211bp_merged|NA|NA|NA|NA",
                    "ASV_2_208bp_merged|NA|NA|NA|NA",
                    "ASV_79_170bp_merged|NA|NA|NA|Hydrochaeris hydrochaeris isol",
                    "ASV_95_169bp_merged|Hominidae|Homo|Homo sapiens|Homo sapiens",
                    "ASV_70_171bp_merged|Hominidae|Homo|Homo sapiens|Homo sapiens",
                    "ASV_87_169bp_merged|Canidae|Canis|Canis familiaris|Canis familiaris",
                    "ASV_89_169bp_merged|Canidae|Canis|Canis familiaris|Canis familiaris",
                    "ASV_71_171bp_merged|NA|NA|NA|Oryctolagus cuniculus mitochon",
                    "ASV_80_170bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_78_170bp_merged|NA|NA|NA|Sus scrofa isolate Europe hapl",
                    "ASV_106_169bp_merged|NA|NA|NA|Sus scrofa breed Andaman Desi ",
                    "ASV_76_170bp_merged|NA|NA|NA|Didelphis albiventris mitochon",
                    "ASV_182_167bp_merged|NA|NA|NA|Cavia magna 12S ribosomal RNA ",
                    "ASV_61_172bp_merged|Hominidae|Homo|Homo sapiens|Homo sapiens",
                    "ASV_73_171bp_merged|Hominidae|Homo|Homo sapiens|Homo sapiens",
                    "ASV_72_171bp_merged|Hominidae|Homo|Homo sapiens|Homo sapiens",
                    "ASV_190_160bp_merged|Hominidae|Homo|Homo sapiens|Homo sapiens",
                    "ASV_99_169bp_merged|NA|NA|NA|NA",
                    "ASV_96_169bp_merged|NA|NA|NA|Hydrochaeris hydrochaeris isol",
                    "ASV_105_169bp_merged|NA|NA|NA|Hydrochaeris hydrochaeris isol",
                    "ASV_108_169bp_merged|NA|NA|NA|Hydrochaeris hydrochaeris isol",
                    "ASV_101_169bp_merged|NA|NA|NA|NA",
                    "ASV_93_169bp_merged|NA|NA|NA|NA",
                    "ASV_91_169bp_merged|NA|NA|NA|NA",
                    "ASV_92_169bp_merged|NA|NA|NA|NA",
                    "ASV_122_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_111_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_112_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_123_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_120_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_132_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_119_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_116_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_118_168bp_merged|Bovidae|Bos|Bos taurus|Bos taurus",
                    "ASV_192_158bp_merged|NA|NA|NA|Human DNA sequence from clone ",
                    "ASV_28_181bp_merged|NA|NA|NA|Progne chalybea mitochondrion,",
                    "ASV_29_180bp_merged|NA|NA|NA|Nannopterum brasilianus mitoch") 

dna_fasta_fil <- dna_fasta_or[!(names(dna_fasta_or) %>% str_detect(pattern = "Out")) & ## removendo as ASVs com "Out" no header
                                   !(names(dna_fasta_or) %in% asvs_to_remove)] #removendo as ASVs que estão na lista asvs_to_remove
                                   
# Verificar quais sequências foram filtradas
filtrado <- names(dna_fasta_or[!(names(dna_fasta_or) %in% names(dna_fasta_fil))]) # os nomes foram armazenados no objeto filtrado

# Verificar as as ASVs que sobraram mas não estão na lista de seqs para filtrar
filtrado[!filtrado %in% asvs_to_remove] #este resultado possui apenas as sequências externas, ja que elas foram retiradas com o str_detect

# Verificar quais nomes estão na lista de seqs para filtrar mas não foram filtradas
asvs_to_remove[!asvs_to_remove %in% filtrado]

BrowseSeqs(dna_fasta_or)
BrowseSeqs(dna_fasta_fil)

# Alinhar as seqs ----

dna_fasta_falgn <- DECIPHER::AlignSeqs(myXStringSet = dna_fasta_fil, 
                                      refinements = 100,
                                      iterations = 100,
                                      verbose = TRUE)
BrowseSeqs(dna_fasta_falgn)

# Salvar o alinhamento

Biostrings::writeXStringSet(x = dna_fasta_falgn,
                            file =  "/home/gabriel/projetos/lagoa_ingleses/tree/asvs-LI_db.fasta")

# Calcular a matriz de distancia ----
dna_dist <- DECIPHER::DistanceMatrix(myXStringSet = dna_fasta_falgn,
                                            # includeTerminalGaps = TRUE,
                                            includeTerminalGaps = FALSE,      #test both versions on the final output
                                            correction = "Jukes-Cantor",
                                            processors = 20,
                                            verbose = TRUE)

# Construcao do Heatmap ----

## Visualizar as seqs de ASVs que mais destoam do conjunto principal
## Nao estava sendo possivel construir a arvore por causa de valores infinitos na matriz.
## Por esse motivo, plotamos esse heatmap que favorece a visualizacao das sequencias que 
## estao tendo distancia infinita em relacao as outras

# Transformar os valores de INF em 1 para poder ler a matriz com o heatmap
dna_dist[is.infinite(dna_dist)] <- 1

# Heatmap
pheatmap::pheatmap(dna_dist,
                   fontsize = 1,
                   col = brewer.pal(n = 9,name = "YlOrRd"),
                   treeheight_col = 0,
                   filename = "/home/gabriel/projetos/lagoa_ingleses/tree/heatmap_dist.pdf", ## avaliar quais ASVs estao sendo outliers abrindo o pdf e olhando seus nomes
                   width = 8,
                   height = 6
                   )

# Retirar do conjunto de ASVs as sequencias distoantes

dna_fasta_tree[!dna_fasta_tree == ""]



# Construir arvore ----

dna_tree <- ape::njs(dna_dist)

# Plot tree tow view ----
dna_tree_plot <- ggtree(tr = dna_tree) + 
  theme_tree2() +
  geom_tiplab(offset = 0,align = T) + 
  xlim(0, 2)

print(dna_tree_plot)

dna_tree_plot %>% ggsave(filename = "/home/gabriel/projetos/lagoa_ingleses/tree/asv-LI_db_tree.pdf", 
                         device = "pdf",width = 12,height = 40)

# Salvar arvore ----
ape::write.tree(phy = dna_tree,file = "~/projetos/lagoa_ingleses/tree/asv-LI_db_tree.nwk")

# Customize (manually)-----

## on MEGA software, drag and drop the .nwk file. Use tools to generate a pretty visualization
```
