---
  title: "Correlation plots Lagoa dos Ingleses "
author: "Gabriel Mendes"
date: "01/2024"
---
  
  # Carregando bibliotecas ----
{
  library(Biostrings)
  library(DECIPHER)
  library(factoextra)
  library(future)
  library(ggh4x)
  library(ggord)
  library(ggpubr)
  library(ggvegan)
  library(Matrix)
  library(phyloseq)
  library(ShortRead)
  library(stringr)
  library(vegan)
  library(tidyverse)
  library(dplyr)
}

# Caminhos ----
{
  prjct_path <- "~/projetos/lagoa_ingleses/"
  results_path <- paste0(prjct_path,"/results")
  figs_path <- paste0(results_path,"/figuras")
  tbl_path <- paste0(prjct_path,"/tabelas/raw/run_2_4_5")
  prjct_radical <- "eDNA_Lagoa-dos-Ingleses"
}

# Obtencao de dados ----

# All the data was generated by the 012024_post_plot.r code

# Selecionando as informacoes necessarias

View(fish_ID_tbl) # Tabela principal
colnames(fish_ID_tbl)

resume_tbl <- fish_ID_tbl %>% 
  # select(Sample, `Curated ID`, filter, RRA) %>% 
  filter(expedition %in% c("Novembro 2021")) %>% 
  group_by(Sample, filter) %>% 
  mutate("Sample total abundance" = sum(Abundance)) %>% 
  ungroup() %>% 
  group_by(`Curated ID`, `filter`) %>% 
  reframe("ID rel. abd. on sample" =  sum(Abundance)/mean(`Sample total abundance`)) %>% 
  ungroup()

View(resume_tbl)

# Pivotar a tabela para realizar a correlacao

IDs_samples_abd <- clean_res_tbl_abd %>% 
  select(-c(`Unique sample name`)) %>% 
  pivot_wider(id_cols = c("Sample","curated final ID"), names_from = "Primer",values_from = "ID rel. abd. on sample")  %>% 
  mutate_if(is.numeric, replace_na, replace = 0)

pivot_IDs_abd <- resume_tbl %>%
  pivot_wider(id_cols = c("Curated ID"), 
              names_from = "filter", 
              values_from = "ID rel. abd. on sample") %>% 
  mutate_if(is.numeric, replace_na, replace = 0)

# Plotar as correlacoes

# MCE Vs. Sterivex ----
options(scipen=999)
  corr_MCE_STX <- pivot_IDs_abd %>% 
  ggplot(aes(x = MCE,
             y = Sterivex
             )) +
  geom_point(aes()) +
  coord_fixed(xlim= c(-0.1,1.1),
              ylim= c(-0.1,1.1)) +
  geom_smooth(method = "lm",se = T) +
    scale_x_log10(oob = scales::squish_infinite) +
    scale_y_log10(oob = scales::squish_infinite) +
    stat_cor(method="pearson") 

  
  # Salvar em pdf 
  ggsave(plot = corr_MCE_STX, 
         filename = paste("/home/gabriel/projetos/lagoa_ingleses/results/figuras/2024/",
                          "corr_MCE_STX", "-", Sys.Date(), ".pdf", sep = ""),
         device = "pdf",
         units = "cm",
         height = 25,
         width = 15,
         dpi = 600)















