---
title: "Boxplot Lagoa dos Ingleses "
author: "Gabriel Mendes"
date: "01/2024"
---
  
# Carregando bibliotecas ----
{
  library(Biostrings)
  library(DECIPHER)
  library(factoextra)
  library(future)
  library(ggh4x)
  library(ggord)
  library(ggpubr)
  library(ggvegan)
  library(Matrix)
  library(phyloseq)
  library(ShortRead)
  library(stringr)
  library(vegan)
  library(tidyverse)
  library(dplyr)
}

# Caminhos ----
{
  prjct_path <- "~/projetos/lagoa_ingleses/"
  results_path <- paste0(prjct_path,"/results")
  figs_path <- paste0(results_path,"/figuras")
  tbl_path <- paste0(prjct_path,"/tabelas/raw/run_2_4_5")
  prjct_radical <- "eDNA_Lagoa-dos-Ingleses"
}

# Obtencao de dados ----

# All the data was generated by the 012024_post_plot.r code

  ## Boxplot
  
  index_df <- fish_ID_tbl %>%
    filter(expedition %in% c("Novembro 2021")) %>% 
    # group_by(Sample,Nivel) %>% 
    group_by(Sample,filter) %>% 
    summarise("Species" = length(unique(`Curated ID`))) %>%
    # mutate(Nivel = ifelse(Nivel == "Cheio", "Full", "Empty")) %>%
    # mutate(Nivel = factor(Nivel, levels = c("Full", "Empty"))) %>% 
    as.data.frame()
  
  # compare_means(Species ~ Nivel, data=index_df, method = "t.test", paired = FALSE)
  compare_means(Species ~ filter, data=index_df, method = "t.test", paired = FALSE)

  boxplot_heron <- fish_ID_tbl %>% 
    filter(expedition %in% c("Novembro 2021")) %>% 
    # group_by(Sample,Nivel) %>% 
    group_by(Sample,filter) %>% 
    reframe("Species" = length(unique(`Curated ID`))) %>%
    # mutate(Nivel = ifelse(Nivel == "Cheio", "Full", "Empty")) %>%
    # mutate(Nivel = factor(Nivel, levels = c("Full", "Empty"))) %>%
    ggplot(aes(x=
                 # Nivel,
                 filter,
               fill=
                 # Nivel,
                 filter,
               y=Species,
               alpha )) +
    geom_boxplot(
      # fill = "blue",
      color = "black",
      size = 0.3) +
    geom_jitter(height = 0.2, width = 0.1, color = "gray")+ 
    theme_minimal() +
    labs(x = "Filtro", y = "Riqueza", title = "Riqueza de Espécies: MCE vs. Sterivex") +
    theme(
      panel.background = element_blank(),
      # panel.grid.major = element_blank(),
      panel.grid.major = element_line(color = "grey",
                                      size = 0.2,
                                      linetype = 1),
      # axis.ticks = element_line(color = "grey"),
      axis.ticks = element_blank(),
      axis.text = element_text(color = "black"),
      axis.title = element_text(color = "black", size = rel(1.2)),
      # legend.background = element_blank(),
      # legend.key = element_blank(),
      legend.text = element_text(color = "black"),
      legend.title = element_text(color = "black", size = rel(1.2)),
      plot.title = element_text(color = "black", size = rel(1.5)),
      plot.subtitle = element_text(color = "black", size = rel(1.2)),
      strip.background = element_rect(fill = "#e4e4e4"),
      strip.text = element_text(color = "black", size = rel(1.2))) +
    theme(plot.title = element_text(size = 20, face = "bold"),
          axis.text.x = element_text(size = 14, hjust = 1, vjust = 1),
          axis.text.y = element_text(size = 14),
          axis.title.x = element_text(size = 14, face = "bold"),
          axis.title.y = element_text(size = 14, face = "bold"),
          strip.text = element_text(size = 14, face = "bold"),
          strip.text.y = element_text(angle=0),
          legend.text = element_text(size = 13),
          legend.title = element_text(size = 14),
          legend.position = "bottom"
    ) +
    scale_fill_manual(values = c("#f1c232",
                                 "#3381b1")) +
    labs(x = "Filtro",
         y = "Riqueza",
         fill ='Tipo de filtro',
         title = "Riqueza de espécies",
         subtitle = "Filtro MCE versus Sterivex") +
    # P-value no grafico
    stat_compare_means(label.x = 0.60)
  
  boxplot_heron
  
  # Salvar em pdf
  ggsave(plot =  boxplot_heron, 
         filename = paste("/home/gabriel/projetos/lagoa_ingleses/results/figuras/2024/",
                          "boxplot_MCE_Sterivex", "-", Sys.Date(), ".pdf", sep = ""),
         device = "pdf",
         units = "cm",
         height = 20,
         width = 10,
         dpi = 600) 