---
title: "Alpha plots Lagoa dos Ingleses "
author: "Gabriel Mendes"
date: "01/2024"
---

# Carregando bibliotecas ----
{
  library(Biostrings)
  library(DECIPHER)
  library(factoextra)
  library(future)
  library(ggh4x)
  library(ggord)
  library(ggpubr)
  library(ggvegan)
  library(Matrix)
  library(phyloseq)
  library(ShortRead)
  library(stringr)
  library(vegan)
  library(tidyverse)
  library(dplyr)
}

# Obtencao de dados ----

# All the data was generated by the 012024_post_plot.r code 

## Alpha plots ----

# Actinopteri familias proporcoes ----

fish_fam_all <- fish_ID_tbl %>% 
  unite(new_name, year, filter,sep = "_", remove = FALSE, col = "un_amostral") %>% 
  select(c(`Curated Order (BLASTn)`, `Family (BLASTn)`,`Curated ID`, new_name, year, filter, un_amostral)) %>% 
  unique() %>%
  group_by(new_name, year, filter) %>% 
  mutate("alpha_d" = length(`Curated ID`)) %>%
  ungroup() %>% 
  group_by(`Family (BLASTn)`,new_name, year, filter) %>% 
  mutate("alpha_d_order" = length(`Curated ID`)) %>% 
  ungroup() %>% 
  mutate("alpha_d_order_%" = round(alpha_d_order/alpha_d*100, digits = 2)) %>% 
  select(-c(`Curated ID`)) %>% 
  unique() %>% 
  group_by(un_amostral) %>% 
  mutate(ano_nivel = case_when(
    year == "2020" ~ "2020 - Cheio",
    year == "2021" ~ "2021 - Vazio",
    year == "2022" ~ "2022 - Cheio"
  )) %>%
  filter(filter %in% "MCE") %>% 
  ggplot(aes(x = new_name,
             y = alpha_d_order,
             fill = `Family (BLASTn)`)) +
  geom_col(position = "fill") +
  geom_text(aes( #adicionando % dentro das barras
    label = sprintf("%0.1f%%",`alpha_d_order_%`)),
    position = position_fill(vjust = 0.5),
    color = "black") +
  facet_grid(rows = vars(ano_nivel
                         # , filter
                         ),
             space = "free", 
             scales = "free",
             drop = TRUE) +
  coord_flip() + #virando 90o o grafico
  guides(fill = guide_legend("Família")) + ## alterar o titulo da legenda 
  theme(
    # panel.background = element_blank(),
    # panel.grid.major = element_blank(),
    panel.grid.major = element_line(color = "grey",
                                    size = 0.2,
                                    linetype = 1),
    axis.ticks = element_blank(),
    axis.text = element_text(color = "black"),
    axis.title = element_text(color = "black", size = rel(1.2)),
    legend.text = element_text(color = "black"),
    legend.title = element_text(color = "black", size = rel(1.2)),
    plot.title = element_text(color = "black", size = rel(1.5)),
    plot.subtitle = element_text(color = "black", size = rel(1.2)),
  ) +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 20), ## definindo o tamanho de cada texto
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        legend.text = element_text(size = 19),
        legend.title = element_text(size = 19),
        strip.text = element_text(size = 15, face = "bold"),
        legend.position = "bottom",
        legend.background = element_rect(fill = "lightgray", color = NA)) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = c("#256676",
                               "#41c9dc",
                               "#d60724",
                               "#a6e590",
                               "#69306e",
                               "#84ee15",
                               "#531ce8",
                               "#64903a",
                               "#c637bc",
                               "#34f199",
                               "#873c1a",
                               "#f4cacb",
                               "#0b5313",
                               "#68affc",
                               "#1642cd",
                               "#ffa8ff",
                               "#21a708",
                               "#9e73b8",
                               "#f3d426",
                               "#cc7b6f",
                               "#fea53b",
                               "#4d4815"),
                    breaks = "Family (BLASTn)" +
                    name = "Curated Order (BLASTn)") +
  labs(x = "Local",
       y = "Proporção",
       title = "Proporções de famílias identificadas",
       subtitle = "Todas amostras")

fish_fam_all

ggsave(plot = fish_fam_all, 
       filename = paste("/home/gabriel/projetos/lagoa_ingleses/results/figuras/2024/",
                        "alpha_fam_all_PER", "-", Sys.Date(), ".pdf", sep = ""),
       device = "pdf", units = "cm", height = 21, width = 40, dpi = 600)

## Plot alternativo
## https://stackoverflow.com/questions/72636908/can-i-group-items-in-a-legend-in-ggplot2

# Actinopteri ordens proporcoes ----

  fish_ord_all <- fish_ID_tbl %>% 
  unite(new_name, year, filter,sep = "_", remove = FALSE, col = "un_amostral") %>% 
  select(c(`Curated Order (BLASTn)`,`Curated ID`, new_name, year, filter, un_amostral)) %>% 
  unique() %>%
  group_by(new_name, year, filter) %>% 
  mutate("alpha_d" = length(`Curated ID`)) %>%
  ungroup() %>% 
  group_by(`Curated Order (BLASTn)`,new_name, year, filter) %>% 
  mutate("alpha_d_order" = length(`Curated ID`)) %>% 
  ungroup() %>% 
  mutate("alpha_d_order_%" = round(alpha_d_order/alpha_d*100, digits = 2)) %>% 
  select(-c(`Curated ID`)) %>% 
  unique() %>% 
  group_by(un_amostral) %>% 
  mutate(ano_nivel = case_when(
    year == "2020" ~ "2020 - Cheio",
    year == "2021" ~ "2021 - Vazio",
    year == "2022" ~ "2022 - Cheio"
  )) %>%
  filter(filter %in% "MCE") %>% 
  ggplot(aes(x = new_name,
             y = alpha_d_order,
             # y = length(`Curated ID`),
             # y = RRA,
             fill = `Curated Order (BLASTn)`)) +
  geom_col(position = "fill") +
  geom_text(aes( # adicionar % dentro das barras
    label = sprintf("%0.1f%%",`alpha_d_order_%`)),
    position = position_fill(vjust = 0.5),
    color = "white") +
  facet_grid(rows = vars(ano_nivel
                         # , 
                         # filter
                         ),
             space = "free", 
             scales = "free",
             drop = TRUE) +
  coord_flip() + #virando 90o o grafico
  guides(fill = guide_legend("Ordens")) + ## alterar o titulo da legenda 
  theme(
    panel.grid.major = element_line(color = "grey",
                                    size = 0.2,
                                    linetype = 1),
    axis.ticks = element_blank(),
    axis.text = element_text(color = "black"),
    axis.title = element_text(color = "black", size = rel(1.2)),
    legend.text = element_text(color = "black"),
    legend.title = element_text(color = "black", size = rel(1.2)),
    plot.title = element_text(color = "black", size = rel(1.5)),
    plot.subtitle = element_text(color = "black", size = rel(1.2)),
  ) +
  theme(plot.title = element_text(size = 20, face = "bold"),
        axis.text.x = element_text(size = 20), ## definindo o tamanho de cada texto
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 20, face = "bold"),
        axis.title.y = element_text(size = 20, face = "bold"),
        legend.text = element_text(size = 19),
        legend.title = element_text(size = 19),
        strip.text = element_text(size = 15, face = "bold"),
        legend.position = "bottom",
        legend.background = element_rect(fill = "lightgray", color = NA)) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = c("#a64595",
                               "#34466d", 
                               "#429369",
                               "#881c23",
                               "#c0710c",
                               "#7e80af",
                               "#195036",
                               "#c5667d", 
                               "#cf6449",
                               "#53348e")) +
  labs(x = "Local",
       y = "Proporção",
       title = "Proporções de ordens identificadas",
       subtitle = "Todas amostras") 

fish_ord_all

ggsave(plot = fish_ord_all, 
       filename = paste("/home/gabriel/projetos/lagoa_ingleses/results/figuras/2024/",
                        "alpha_ord_all_PER", "-", Sys.Date(), ".pdf", sep = ""),
       device = "pdf", units = "cm", height = 20, width = 40, dpi = 600)

